### ISSUE TITLE
checkbox

### ISSUE THREAD

**Issue by m00h0** [newtonah0/todo-list#4]
I have issues with my checkbox.

**Comment by AliRezaBmeDu** [comment]
Please recheck your addTask function, Because it seems the checkboxes initialized with the status false everytime you load the page.

**Comment by mumbereh** [comment]
In the HTML, add an <input type="checkbox"> element with a unique id attribute. In CSS, use the adjacent sibling selector (+) to target the checkbox and apply text-decoration: line-through to the label. In JS, add an event listener to the checkbox and toggle a class on the label to trigger the strikethrough effect.
